# Generated by Django 3.2.23 on 2025-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(help_text='OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(help_text='Truckstop Name', max_length=255)),
                ('address', models.TextField(help_text='Full address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(help_text='Rack ID')),
                ('retail_price', models.DecimalField(decimal_places=3, help_text='Retail price per gallon', max_digits=6)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geocoded', models.BooleanField(default=False, help_text='Whether this station has been geocoded')),
            ],
            options={
                'ordering': ['retail_price'],
            },
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['state', 'retail_price'], name='planner_fue_state_caedfb_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['geocoded'], name='planner_fue_geocode_a9d260_idx'),
        ),
    ]
